sudo: required
services:
  - docker
language: python
python:
  - "2.7"
install: "pip install -r dev-requirements.txt"
script: ./hack/run-tests -c
addons:
  artifacts:
    paths:
      - ./coveragereport
